# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20150514_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidruser',
            name='display_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=30, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='bidruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='bidruser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='bidruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
